version: '3.8'
services:
  api:
    build:
      context: ./api
    ports:
      - '8080:3005'
    environment:
      PORT: '3005'
      PROXY_API_URL: 'https://mockapi-furw4tenlq-ez.a.run.app/data'
      CORS_CLIENT_ORIGIN: 'http://webapp:3000'

  db:
    image: 'postgres:16'
    ports:
      - '54320:5432'
    volumes:
      - db_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'testpass'

  webapp:
    depends_on:
      - api
      - db
    build:
      dockerfile: webapp/Dockerfile
      context: .
    environment:
      - POSTGRES_PRISMA_URL=postgresql://postgres:testpass@db:5432/mydb?schema=public
      - API_TRPC_URL=http://api:3005/trpc
    ports:
      - '8082:3000'
      # - $WEBAPP_LOCAL_PORT:$WEBAPP_DOCKER_PORT

volumes:
  db_pg_data:
