export const data = [
  [
    {
      client_id: '849676cb',
      date_testing: '2018-07-25',
      date_birthdate: '1950-01-01',
      gender: 2,
      ethnicity: 5,
      creatine: 0.48,
      chloride: 101.66,
      fasting_glucose: 138.44,
      potassium: 1.87,
      sodium: 93.31,
      total_calcium: 14.74,
      total_protein: 14.56,
      creatine_unit: 'mgdl',
      chloride_unit: 'mmoll',
      fasting_glucose_unit: 'mgdl',
      potassium_unit: 'mmoll',
      sodium_unit: 'ul',
      total_calcium_unit: 'mgdl',
      total_protein_unit: 'gdl',
    },
    {
      client_id: '849676cb',
      date_testing: '2018-10-03',
      date_birthdate: '1950-01-01',
      gender: 2,
      ethnicity: 5,
      creatine: 0.41,
      chloride: 106.2,
      fasting_glucose: 62.32,
      potassium: 8.48,
      sodium: 145.76,
      total_calcium: 8.78,
      total_protein: 8.58,
      creatine_unit: 'mgdl',
      chloride_unit: 'mmoll',
      fasting_glucose_unit: 'mgdl',
      potassium_unit: 'mmoll',
      sodium_unit: 'ul',
      total_calcium_unit: 'mgdl',
      total_protein_unit: 'gdl',
    },
    {
      client_id: '849676cb',
      date_testing: '2019-07-06',
      date_birthdate: '1950-01-01',
      gender: 2,
      ethnicity: 5,
      creatine: 0.2,
      chloride: 101.57,
      fasting_glucose: 85.55,
      potassium: 3.6,
      sodium: 144.21,
      total_calcium: 13.5,
      total_protein: 11.01,
      creatine_unit: 'mgdl',
      chloride_unit: 'mmoll',
      fasting_glucose_unit: 'mgdl',
      potassium_unit: 'mmoll',
      sodium_unit: 'ul',
      total_calcium_unit: 'mgdl',
      total_protein_unit: 'gdl',
    },
    {
      client_id: '849676cb',
      date_testing: '2020-01-21',
      date_birthdate: '1950-01-01',
      gender: 2,
      ethnicity: 5,
      creatine: 0.92,
      chloride: 112.9,
      fasting_glucose: 79.38,
      potassium: 5.73,
      sodium: 54.72,
      total_calcium: 11.71,
      total_protein: 6.79,
      creatine_unit: 'mgdl',
      chloride_unit: 'mmoll',
      fasting_glucose_unit: 'mgdl',
      potassium_unit: 'mmoll',
      sodium_unit: 'ul',
      total_calcium_unit: 'mgdl',
      total_protein_unit: 'gdl',
    },
    {
      client_id: '849676cb',
      date_testing: '2020-06-21',
      date_birthdate: '1950-01-01',
      gender: 2,
      ethnicity: 5,
      creatine: 0.83,
      chloride: 82.79,
      fasting_glucose: 90.81,
      potassium: 2.75,
      sodium: 76.77,
      total_calcium: 12.68,
      total_protein: 7.15,
      creatine_unit: 'mgdl',
      chloride_unit: 'mmoll',
      fasting_glucose_unit: 'mgdl',
      potassium_unit: 'mmoll',
      sodium_unit: 'ul',
      total_calcium_unit: 'mgdl',
      total_protein_unit: 'gdl',
    },
    {
      client_id: '849676cb',
      date_testing: '2020-07-06',
      date_birthdate: '1950-01-01',
      gender: 2,
      ethnicity: 5,
      creatine: 0.42,
      chloride: 95.41,
      fasting_glucose: 111.6,
      potassium: 5.37,
      sodium: 130.16,
      total_calcium: 12.78,
      total_protein: 5.81,
      creatine_unit: 'mgdl',
      chloride_unit: 'mmoll',
      fasting_glucose_unit: 'mgdl',
      potassium_unit: 'mmoll',
      sodium_unit: 'ul',
      total_calcium_unit: 'mgdl',
      total_protein_unit: 'gdl',
    },
    {
      client_id: '849676cb',
      date_testing: '2020-11-22',
      date_birthdate: '1950-01-01',
      gender: 2,
      ethnicity: 5,
      creatine: 0.5,
      chloride: 95.47,
      fasting_glucose: 144.96,
      potassium: 4.85,
      sodium: 72.47,
      total_calcium: 9.08,
      total_protein: 10.98,
      creatine_unit: 'mgdl',
      chloride_unit: 'mmoll',
      fasting_glucose_unit: 'mgdl',
      potassium_unit: 'mmoll',
      sodium_unit: 'ul',
      total_calcium_unit: 'mgdl',
      total_protein_unit: 'gdl',
    },
    {
      client_id: '849676cb',
      date_testing: '2021-09-25',
      date_birthdate: '1950-01-01',
      gender: 2,
      ethnicity: 5,
      creatine: 0.27,
      chloride: 109.23,
      fasting_glucose: 128.21,
      potassium: 5.51,
      sodium: 142.59,
      total_calcium: 10.98,
      total_protein: 8.73,
      creatine_unit: 'mgdl',
      chloride_unit: 'mmoll',
      fasting_glucose_unit: 'mgdl',
      potassium_unit: 'mmoll',
      sodium_unit: 'ul',
      total_calcium_unit: 'mgdl',
      total_protein_unit: 'gdl',
    },
  ],
];
